### ISSUE TITLE
44P版本点击：“每日答题等”报错

### ISSUE THREAD

**Issue by ID435858113** [lolisaikou/LazyStudy#13]
你的手机型号：Redmi   K30 pro

你的安卓版本：安卓10

错误的截图：

![微信图片_20200722102537](https://user-images.githubusercontent.com/67099372/88127196-b4e48780-cc05-11ea-96ca-792ad2b31af7.jpg)

错误描述：10:19:43.157/E: Thread[ScriptThread-2[/data/user/0/com.lazyxue.onekey/files/project/floating.js] (Spawn-1),5]: TypeError:     无法调用undefined的方法"forEach" (file:/data/data/com.lazyxue.onekey/files/project/dailyAnswer.js#257)
TypeError:     无法调用undefined的方法"forEach"
    at dailyQuestionLoop (file:/data/data/com.lazyxue.onekey/files/project/dailyAnswer.js:257:0)
    at dailyQuestion (file:/data/data/com.lazyxue.onekey/files/project/dailyAnswer.js:336:0)
    at main (file:/data/data/com.lazyxue.onekey/files/project/dailyAnswer.js:368:0)
    at /data/user/0/com.lazyxue.onekey/files/project/floating.js:94:0

**Comment by lolisaikou** [comment]
答题功能没有加错误判断，请在进入每周、每日或专项答题的时候再点击“每日答题等”按钮
下个版本会修复
