### ISSUE TITLE
大神 这个软件你还更新么？   获取不了题库了

### ISSUE THREAD

**Issue by ID-JRL** [lolisaikou/LazyStudy#138]
你的手机型号：

你的安卓版本：

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：

**Comment by LumiaJ** [comment]
> 你的手机型号：
> 
> 你的安卓版本：
> 
> 错误的截图：
> （可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）
> 
> 错误描述：

00:18:19.590/E: Thread[main,5]: Wrapped javax.net.ssl.SSLHandshakeException: Chain validation failed (file:/data/user/0/com.lazyxue.onekey/files/project/updateTikuNet.js#62)
Wrapped javax.net.ssl.SSLHandshakeException: Chain validation failed
    at updateTikunet (file:/data/user/0/com.lazyxue.onekey/files/project/updateTikuNet.js:62:0)
    at UI.js.js:309:0
