### ISSUE TITLE
44p版本无法使用问题

### ISSUE THREAD

**Issue by 2503449779** [lolisaikou/LazyStudy#14]
你的手机型号：华为 Honor 9X

你的安卓版本：10

错误的截图：
https://ftp.bmp.ovh/imgs/2020/07/a6c3fbab66ffa863.jpg
https://ftp.bmp.ovh/imgs/2020/07/7d37b16986e5b62d.jpg

错误描述：无法获取积分 显示NaN
答题显示错误

**Comment by lolisaikou** [comment]
能正常阅读文章或者答题吗？

**Comment by 2503449779** [comment]
> 能正常阅读文章或答题吗？

你好，试过了原作者的版本和您修改的版本都不行，原作者的3.1.2版本只有挑战答题可用

**Comment by lolisaikou** [comment]
> > 能正常阅读文章或答题吗？
> 
> 你好，试过了原作者的版本和您修改的版本都不行，原作者的3.1.2版本只有挑战答题可用

第一张图：是你用法不对，两个答题按钮都需要在对应的答题界面按才能用
第二张：可能只是分数无法输出到悬浮窗里，我看到你截图的时候，程序应该在订阅强国号，说明程序在正常运行

**Comment by 2503449779** [comment]
> > > 能正常阅读文章或答题吗？
> > 
> > 
> > 你好，试过了原作者的版本和您修改的版本都不行，原作者的3.1.2版本只有挑战答题可用
> 
> 第一张图：是你用法不对，两个答题按钮都需要在对应的答题界面按才能用
> 第二张：可能只是分数无法输出到悬浮窗里，我看到你截图的时候，程序应该在订阅强国号，说明程序在正常运行

https://ftp.bmp.ovh/imgs/2020/07/be047e55e542ff33.jpg
https://ftp.bmp.ovh/imgs/2020/07/f46867818258cedf.jpg
在对应答题页面使用的，挑战题是跳徐特立
订阅操作是没有订阅到的 分数确实无法输出
也不知道为什么
能打开的只有本地频道 其他都不行
出现了崩溃日志
Version: 8000005
Android: 29

Error: java.lang.IllegalArgumentException: View=com.stardust.widget.ViewSwitcher{4ad4149 VFE...... ......ID 0,0-1016,1030 #7f090070 app:id/container} not attached to window manager

java.lang.IllegalArgumentException: View=com.stardust.widget.ViewSwitcher{4ad4149 VFE...... ......ID 0,0-1016,1030 #7f090070 app:id/container} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:597)
	at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:471)
	at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:131)
	at a.g.c.g$a.updatePosition(Unknown Source:10)
	at a.g.c.c$b.updatePosition(Unknown Source:0)
	at com.stardust.autojs.core.console.ConsoleImpl.a(Unknown Source:10)
	at a.g.b.o.b.f.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8349)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by lolisaikou** [comment]
崩溃是脚本解释器本身的问题，我这里也出现过，不是很清楚怎么解决

强国版本是多少？最新的吗？

**Comment by 2503449779** [comment]
> 崩溃是脚本解释器本身的问题，我这里也出现过，不是很清楚怎么解决
> 
> 强国版本是多少？最新的吗？

2.12.0（12960734）

**Comment by lolisaikou** [comment]
升级到最新版本吧，旧版本应该不支持了，最新版：2.14.1
![image](https://user-images.githubusercontent.com/32028165/88452370-c7262600-ce90-11ea-8136-6373cf75dd2e.png)

**Comment by 2503449779** [comment]
> 升级到最新版本吧，旧版本应该不支持了，最新版：2.14.1
> ![image](https://user-images.githubusercontent.com/32028165/88452370-c7262600-ce90-11ea-8136-6373cf75dd2e.png)

看见了 试了下可以！谢谢了 因为软件没提示更新以为是最新的了
