### ISSUE TITLE
2.7.0无法使用

### ISSUE THREAD

**Issue by 1761630764** [lolisaikou/LazyStudy#69]
你的手机型号：

你的安卓版本：

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：

**Comment by 1761630764** [comment]
lanzystudy
1加
安卓10
截图：https://ftp.bmp.ovh/imgs/2020/10/3f0c4056703597e3.jpg
描述；一直加载等待主页面     没有反应

错误信息Version: 8020100
Android: 29

Error: java.lang.IllegalArgumentException: View=com.stardust.widget.ViewSwitcher{a256ed7 VFE...... ......ID 0,0-720,640 #7f090073 app:id/container} not attached to window manager

java.lang.IllegalArgumentException: View=com.stardust.widget.ViewSwitcher{a256ed7 VFE...... ......ID 0,0-720,640 #7f090073 app:id/container} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:528)
	at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:422)
	at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:103)
	at c.g.c.g$a.updatePosition(Unknown Source:10)
	at c.g.c.c$b.updatePosition(Unknown Source:0)
	at com.stardust.autojs.core.console.ConsoleImpl.c(Unknown Source:10)
	at c.g.b.o.b.f.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by no1ajian** [comment]
我也一样 小米4C

**Comment by hanguowei98** [comment]
使用懒人APP的用户，建议不要更新强国，使用强国2.15.0版本就行了阿！

**Comment by haoguowei98** [comment]
使用源码的，可以参考下@Ivan-cn 的修改意见，“
把所有的("学习")改成("工作")，42分专版（onekey）的通过。”

**Comment by hanguowei98** [comment]
使用源码的，可以参考下@Ivan-cn 的修改意见，“把所有的("学习")改成("工作")，42分专版（onekey）的通过。”

**Comment by whliziwen** [comment]
同样问题，有更新吗

**Comment by abapop** [comment]
> 使用源码的，可以参考下@Ivan-cn 的修改意见，“把所有的("学习")改成("工作")，42分专版（onekey）的通过。”

在哪里怎么修改呀？

**Comment by KB64ba** [comment]
while/if(!desc("学习").exists());
把while和if判断是否在学习界面的都改为下面这个
while(!(desc("学习").exists() || desc("工作").exists()));//等待加载出主页
